### ISSUE TITLE
Extension not loading in FreshRss

### ISSUE THREAD

**Issue by designworld-ca** [printfuck/xExtension-Readable#13]
I added the suggested configuration to the docker-compose.yml as services and can see in docker that the three services are up and running.  In the FreshRss extensions section Readable does not show up as a working extension.

The only issue in the FreshRss logs is many entries for "Error while WebSub subscribing to...." which does not seem relevant.

Where would I look for further diagnostic information?

**Comment by designworld-ca** [comment]
Where would I set the server FQDN?
Logs indicate:

fivefilters-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
fivefilters-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
fivefilters-1  | [Thu Nov 28 15:21:59.022235 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/5.6.40 configured -- resuming normal operations
fivefilters-1  | [Thu Nov 28 15:21:59.022301 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
freshrss       | [migrations] started
freshrss       | [migrations] 01-nginx-site-confs-default: skipped
freshrss       | [migrations] 02-default-location: skipped
freshrss       | [migrations] done
freshrss       | ───────────────────────────────────────
freshrss       |
freshrss       |       ██╗     ███████╗██╗ ██████╗
freshrss       |       ██║     ██╔════╝██║██╔═══██╗
freshrss       |       ██║     ███████╗██║██║   ██║
freshrss       |       ██║     ╚════██║██║██║   ██║
freshrss       |       ███████╗███████║██║╚██████╔╝
freshrss       |       ╚══════╝╚══════╝╚═╝ ╚═════╝
freshrss       |
freshrss       |    Brought to you by linuxserver.io
freshrss       | ───────────────────────────────────────
freshrss       |
freshrss       | To support LSIO projects visit:
freshrss       | https://www.linuxserver.io/donate/
freshrss       |
freshrss       | ───────────────────────────────────────
freshrss       | GID/UID
freshrss       | ───────────────────────────────────────
freshrss       |
freshrss       | User UID:    1000
freshrss       | User GID:    1000
freshrss       | ───────────────────────────────────────
freshrss       | Linuxserver.io version: 1.24.3-ls251
freshrss       | Build-date: 2024-11-24T13:09:46+00:00
freshrss       | ───────────────────────────────────────
freshrss       |
freshrss       | using keys found in /config/keys
read-1         | 2024-11-28T15:21:59: PM2 log: Launching in no daemon mode
read-1         | 2024-11-28T15:21:59: PM2 log: App [Readability server:0] starting in -cluster mode-
read-1         | 2024-11-28T15:21:59: PM2 log: App [Readability server:0] online
read-1         | 2024-11-28T15:21:59: PM2 log: App [Readability server:1] starting in -cluster mode-
read-1         | 2024-11-28T15:21:59: PM2 log: App [Readability server:1] online
read-1         | 2024-11-28T15:21:59: PM2 log: App [Readability server:2] starting in -cluster mode-
read-1         | 2024-11-28T15:22:00: PM2 log: App [Readability server:2] online
read-1         | 2024-11-28T15:22:00: PM2 log: App [Readability server:3] starting in -cluster mode-
merc-1         |
merc-1         | > mercury-parser-api@1.0.0 start
merc-1         | > node index.js
merc-1         |
freshrss       | [custom-init] No custom files found, skipping...
read-1         | 2024-11-28T15:22:00: PM2 log: App [Readability server:3] online
read-1         | 2024-11-28T15:22:00: PM2 log: App [Readability server:4] starting in -cluster mode-
freshrss       | [ls.io-init] done.
read-1         | 2024-11-28T15:22:00: PM2 log: App [Readability server:4] online
merc-1         | 🚀Mercury Parser API listens on port 3000
read-1         | [2024-11-28T15:22:04.233Z] Readability.js server v1.7.2 listening on port 3000!
read-1         | [2024-11-28T15:22:04.271Z] Readability.js server v1.7.2 listening on port 3000!
read-1         | [2024-11-28T15:22:04.314Z] Readability.js server v1.7.2 listening on port 3000!
read-1         | [2024-11-28T15:22:04.313Z] Readability.js server v1.7.2 listening on port 3000!
read-1         | [2024-11-28T15:22:04.362Z] Readability.js server v1.7.2 listening on port 3000!

**Comment by designworld-ca** [comment]
By fiddling around I got the extensions to load using this docker compose.  The changes were to use the IP address of the server as FreshRss is on linux server and to change the address of the cache.  But...the extension still does not show as loaded in the FreshRss extensions page and I cannot find the web page to configure individual feeds.

How do I get FreshRss to recognize that the extension is being used?

For Read  at 192.168.0.165:3000 I see

` {"error":"POST (not GET) JSON, like so: {\"url\": \"https://url/to/whatever\"}"}`

For Mercury at  192.168.0.165:3001  I see

`{"message":"Welcome to 🚀mercury-parser-api API! Endpoint: /parser"}`

Five Fingers is the most functional.  At 192.168.0.165:3002 it shows

```Full-Text RSS 3.8 — from [FiveFilters.org](http://fivefilters.org/)
Create full-text feed from feed or webpage URL
Enter URL
Options
Max items
200
 Limit: 1000
Links

preserve
If extraction fails

keep item in feed
Include excerpt

JSON output

Debug```

Docker compose used

```services:
  read:
    image: phpdockerio/readability-js-server
    restart: always
    ports:
      - 192.168.0.165:3000:3000

  merc:
    image: wangqiru/mercury-parser-api
    restart: always
    ports:
      - 192.168.0.165:3001:3000

  fivefilters:
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "./rss-cache:/home/<your user>/runtipi/user-config/cache/rss"
    ports:
      - "192.168.0.165:3002:80"
    restart: always```

**Comment by printfuck** [comment]
Hi there and sorry for answering this late.

It looks like you don't have the extension installed at all. Since this is not in my documentation, it's partly my fault but I will fix this in the next update.

You have to clone this extension into the `extension` folder of FreshRSS. Usually in docker-compose deployments the folder for installing extensions is volume-mounted to a outside directory. eg:
```
  freshrss:
    image: freshrss/freshrss:edge
    restart: unless-stopped
    ports:
      - 127.0.0.1:8083:80
    depends_on:
      - mariadb
    volumes:
      - './config:/var/www/FreshRSS/data'
      - './extensions:/var/www/FreshRSS/extensions' <-- go into this directory and clone this 
                                                        repository (https://github.com/printfuck/xExtension-Readable)
    environment:
      - CRON_MIN=*/20
    links:
      - read:read
```
Afterwards the extension should appear on the extension page.

It is intended, that the extension uses the docker internal hostnames of the different contianers: fivefilters, merc, read. That is why you weren't able query these from the host system, but you already found out how to make them available.

As I said I will try to make my documentation more precise and thank you for providing your problem 😃

**Comment by designworld-ca** [comment]
No problems!  Always more to do.
I cloned the repo with

```
cd /home/<your user>/runtipi/app-data/freshrss/data/freshrss/www/freshrss/extensions
git clone https://github.com/printfuck/xExtension-Readable
Cloning into 'xExtension-Readable'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 118 (delta 56), reused 93 (delta 35), pack-reused 0 (from 0)
Receiving objects: 100% (118/118), 31.85 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (56/56), done.```

FreshRss now knows about the extension and it is turned on. What I cannot find is the gui page where you can set which feeds use the extension.
If I go to management for each feed there are no new additional options.  Where should I look to configure this extension?
Thanks
