### ISSUE TITLE
just a question: is it possible to re-download old articles after plugin installation?

### ISSUE THREAD

**Issue by user9931** [printfuck/xExtension-Readable#14]
maybe its wrong place to ask..
is it possible to re-download old articles after plugin installation without removing and adding the feed it?

**Comment by printfuck** [comment]
This is not possible. At least in this extension. But there is an option in the FreshRss feed settings under Maintenance, that allows to update all feeds, if a selector is present. Maybe this could be reworked to update without a selector, while triggering the hooks, that I'm using or add some additional hooks, that I could integrate.
