### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by sean89503** [printfuck/xExtension-Readable#7]
I cant seem to get the extension to work i get "Unexpected token" here is an output of running `curl -XPOST http://read:3000/ -H "Content-Type: application/json" -d'("url": "https://www.androidcentral.com/accessories/audio/amazon-echo-frames-carrera-eyewear-reveal")'`

`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token ( in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/application/node_modules/body-parser/lib/types/json.js:169:10)<br> &nbsp; &nbsp;at parse (/application/node_modules/body-parser/lib/types/json.js:86:15)<br> &nbsp; &nbsp;at /application/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (/application/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/application/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/application/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:514:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12)</pre>
</body>
</html>`

**Comment by printfuck** [comment]
Hi,

It should work with: 

```
curl -H "Content-Type: application/json" -d'{"url": "https://www.androidcentral.com/accessories/audio/amazon-echo-frames-carrera-eyewear-reveal"}' http://read:3000
```
Using `{}` instead of `()`.

**Comment by sean89503** [comment]
that worked from the CMD but in feedly i get (see picture)
![image](https://github.com/printfuck/xExtension-Readable/assets/22017525/99a30277-6ce7-48f1-a2a6-371a4919b31f)
![image](https://github.com/printfuck/xExtension-Readable/assets/22017525/143754a0-1775-4aec-8f60-ce8521b5f2ad)

**Comment by printfuck** [comment]
Sorry for not reacting, but I came around to try the same feed with the extension as of now. But I don't have this problem. Also I don't have the override_content row, that you probably added somehow. I'd suggest you use the extension as it is or to try a bit more debugging of your own.

hf, gl
