### ISSUE TITLE
Is there a way to include the FiveFilters Full-Text RSS filter?

### ISSUE THREAD

**Issue by dahlbergc** [printfuck/xExtension-Readable#8]
I've found the free version of the [FiveFilters Full-Text filter](https://www.fivefilters.org/full-text-rss/) works slightly better than Mercury or Readability when parsing RSS feeds.  Is there way to include this filter in the Readable extension as a third filter option?

[https://github.com/heussd/fivefilters-full-text-rss-docker](https://github.com/heussd/fivefilters-full-text-rss-docker)

Thank you so much for all of the work you put into this extension!

**Comment by printfuck** [comment]
Thanks,
I wasn't aware, that there was an actively developed fork of this project. It's added and should work now.

**Comment by dahlbergc** [comment]
Thank you so much for the quick inclusion of FiveFliters into the plugin!  Works like a charm!

**Comment by dahlbergc** [comment]
Thank you so much for the quick inclusion of FiveFliters into the plugin! Works like a charm!
